module.exports = {
    firstName: 'firstName',
    lastName: 'lastName',
    email: 'email',
    phone: 'phone',
    telegramId: 'telegramId',
    password: 'password',

    provider: 'provider',
    recipient: 'recipient',
    amount: 'amount',
    serviceCode: 'serviceCode',
    bundleCode: 'bundleCode',
    variationCode: 'variationCode',
    cardNumber: 'cardNumber',
    serviceId: 'serviceId',
    serviceVariation: 'serviceVariation',
    planId: 'planId',
    quantity: 'quantity',
    commissionType: 'commissionType',
    denomination: 'denomination',
    commissionKey: 'commissionKey',
    nameOnCard: 'nameOnCard',
    type: 'type',
    referralCode: 'referralCode',
    referrer: 'referrer',
    creditSource: 'creditSource',
    profileCode: 'profileCode',
};