module.exports = {
    firstName: 'firstName',
    lastName: 'lastName',
    email: 'email',
    phone: 'phone',
    telegramId: 'telegramId',
    password: 'password',

    provider: 'provider',
    recipient: 'recipient',
    amount: 'amount',
    bundleCode: 'bundleCode',
    cardNumber: 'cardNumber',
    serviceId: 'serviceId',
    planId: 'planId',
    quantity: 'quantity',
    commissionType: 'commissionType',
    denomination: 'denomination',
    commissionKey: 'commissionKey',
    nameOnCard: 'nameOnCard',
    type: 'type',
};